### ISSUE TITLE
ISO checksum mismatch when downloading eval-win2012r2-standard 

### ISSUE THREAD

**Issue by ghost** [boxcutter/windows#28] opened 2015-07-08 10:53 UTC
When running `make virtualbox/eval-win2012r2-standard` checksum validation fails with the following error on master (05aea6a6b2ec4c07ea6526eb975b951434acd347 as of today):

```
virtualbox-iso: Download progress: 100%
    virtualbox-iso: Error downloading: checksums didn't match expected: 849734f37346385dac2c101e4aacba4626bb141c
==> virtualbox-iso: ISO download failed.
Build 'virtualbox-iso' errored: ISO download failed.
```

After downloading the ISO manually ([using the iso_url](https://github.com/boxcutter/windows/blob/05aea6a6b2ec4c07ea6526eb975b951434acd347/eval-win2012r2-standard.json#L171-L172)) I checked the checksums. As of today the sha1sum was `5e2ddcaecc91e80a8ce3ec7ae7838f8a3967ed7f`.

cc @erran

**Comment by dylangrafmyre** [comment] 2015-09-23 06:00
I also experienced the same issue with `eval-win2012r2-datacenter` 

```bash
virtualbox-iso: Error downloading: checksums didn't match expected: 849734f37346385dac2c101e4aacba4626bb141c
==> virtualbox-iso: ISO download failed.
Build 'virtualbox-iso' errored: ISO download failed.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: ISO download failed.

==> Builds finished but no artifacts were created.
make: *** [box/virtualbox/eval-win2012r2-datacenter-nocm-1.0.4.box] Error 1
'''

**Comment by DarwinJS** [comment] 2016-08-23 19:00
I am experiencing this as well - only I have the file already downloaded locally.

**Comment by pauby** [comment] 2016-09-12 14:30
Exactly the same as @DarwinJS  - Packer 0.10.1 though.

This issue is over a year old - any progress on it?

**Comment by dragon788** [comment] 2016-09-22 21:03
I'm not sure what exactly is the root cause of this, but rather than have SHA1 repeated once for each builder type I updated mine to use a user variable iso_checksum_type and set it to md5 in the bottom section and the issue appears to have gone away. Not sure why specifying the same thing at the builder level would fail, perhaps somebody updated the templates with SHA1 at the top, but the next person added a newer MD5 at the bottom and the mismatch is killing things? These are the dangers of forks on GitHub if people don't know how to pull in the latest upstream changes before "fixing" things on their own. I tend to delete and recreate my forks between bouts of activity on a repository for exactly that reason.

**Comment by tas50** [comment] 2017-05-06 20:00
This has been fixed on master

**Closed by tas50** 2017-05-06 20:00 UTC
